# Generated by Django 6.0.1 on 2026-01-28 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textcontent', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Commenttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'commenttype',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'section',
            },
        ),
        migrations.CreateModel(
            name='Sectionstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'sectionstatus',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isitclosed', models.BooleanField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('isitmature', models.BooleanField()),
                ('maxstorylength', models.SmallIntegerField(blank=True, null=True)),
                ('maxsectionlength', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'story',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Commentcomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenttypeid', models.IntegerField()),
                ('commentid', models.ForeignKey(db_column='commentid', on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.comment')),
                ('parentcommentid', models.ForeignKey(db_column='parentcommentid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='commentcomment_parentcommentid_set', to='chainlettersstories.comment')),
            ],
            options={
                'db_table': 'commentcomment',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='commenttypeid',
            field=models.ForeignKey(db_column='commenttypeid', on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.commenttype'),
        ),
        migrations.CreateModel(
            name='Sectioncomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenttypeid', models.IntegerField()),
                ('commentid', models.ForeignKey(db_column='commentid', on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.comment')),
                ('parentsectionid', models.ForeignKey(db_column='parentsectionid', on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.section')),
            ],
            options={
                'db_table': 'sectioncomment',
            },
        ),
        migrations.AddField(
            model_name='section',
            name='sectionstatusid',
            field=models.ForeignKey(db_column='sectionstatusid', on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.sectionstatus'),
        ),
        migrations.AddField(
            model_name='section',
            name='storyid',
            field=models.ForeignKey(db_column='storyid', on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.story'),
        ),
        migrations.CreateModel(
            name='Storycomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenttypeid', models.IntegerField()),
                ('commentid', models.ForeignKey(db_column='commentid', on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.comment')),
                ('parentstoryid', models.ForeignKey(db_column='parentstoryid', on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.story')),
            ],
            options={
                'db_table': 'storycomment',
            },
        ),
        migrations.CreateModel(
            name='Tagassingment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storyid', models.ForeignKey(db_column='storyid', on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.story')),
                ('tagid', models.ForeignKey(db_column='tagid', on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.tag')),
            ],
            options={
                'db_table': 'tagassingment',
            },
        ),
        migrations.AddField(
            model_name='story',
            name='userid',
            field=models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.user'),
        ),
        migrations.AddField(
            model_name='section',
            name='userid',
            field=models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.user'),
        ),
        migrations.AddField(
            model_name='comment',
            name='userid',
            field=models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.user'),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('id', 'commenttypeid')},
        ),
    ]
