# Generated by Django 6.0.1 on 2026-03-11 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSegmentByUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeratableSegmentByUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SegmentTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earlier_segment', models.IntegerField()),
                ('earlier_segment_order', models.IntegerField()),
                ('earlier_segment_content', models.CharField()),
                ('final_user', models.IntegerField()),
                ('final_segment_status', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('previous_segment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.segment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.author')),
                ('segment_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.segmentstatus')),
            ],
        ),
        migrations.CreateModel(
            name='ModerationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_it_closed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.author')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.segment')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_it_closed', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('min_segment_length', models.SmallIntegerField(blank=True, null=True)),
                ('max_segment_length', models.SmallIntegerField(blank=True, null=True)),
                ('max_number_of_segments', models.SmallIntegerField(blank=True, null=True)),
                ('max_number_of_branches', models.SmallIntegerField(blank=True, null=True)),
                ('is_it_mature', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.author')),
            ],
        ),
        migrations.AddField(
            model_name='segment',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.story'),
        ),
        migrations.CreateModel(
            name='Tagassingment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.story')),
                ('tagid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.tag')),
            ],
        ),
    ]
