# Generated by Django 6.0.1 on 2026-01-28 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chainlettersstories', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='StoriesUser',
        ),
    ]
