# Generated by Django 6.0.1 on 2026-03-11 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chainlettersstories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='chainlettersstoriesschema.author',
        ),
        migrations.AlterModelTable(
            name='moderationassignment',
            table='chainlettersstoriesschema.moderation_assignment',
        ),
        migrations.AlterModelTable(
            name='segment',
            table='chainlettersstoriesschema.segment',
        ),
        migrations.AlterModelTable(
            name='segmentstatus',
            table='chainlettersstoriesschema.segment_status',
        ),
        migrations.AlterModelTable(
            name='story',
            table='chainlettersstoriesschema.story',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='chainlettersstoriesschema.tag',
        ),
        migrations.AlterModelTable(
            name='tagassingment',
            table='chainlettersstoriesschema.tag_assignment',
        ),
    ]
