# Generated by Django 6.0.1 on 2026-02-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainlettersstories', '0002_rename_user_storiesuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalsectionid', models.CharField()),
                ('sectionid', models.IntegerField()),
                ('sectionorder', models.IntegerField()),
                ('sectioncontent', models.CharField()),
                ('userid', models.IntegerField()),
            ],
            options={
                'db_table': 'sectiontrace',
                'managed': False,
            },
        ),
    ]
