# Generated by Django 6.0.1 on 2026-03-11 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chainlettersstories', '0002_alter_author_table_alter_moderationassignment_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
        migrations.AlterModelTable(
            name='moderationassignment',
            table='moderation_assignment',
        ),
        migrations.AlterModelTable(
            name='segment',
            table='segment',
        ),
        migrations.AlterModelTable(
            name='segmentstatus',
            table='segment_status',
        ),
        migrations.AlterModelTable(
            name='story',
            table='story',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tag',
        ),
        migrations.AlterModelTable(
            name='tagassingment',
            table='tag_assignment',
        ),
    ]
