# Generated by Django 6.0.1 on 2026-03-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainlettersstories', '0003_alter_author_table_alter_moderationassignment_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSegmentByAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeratableSegmentByAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AvailableSegmentByUser',
        ),
        migrations.DeleteModel(
            name='ModeratableSegmentByUser',
        ),
        migrations.RenameField(
            model_name='moderationassignment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='segment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='user',
            new_name='author',
        ),
    ]
