# Generated by Django 6.0.1 on 2026-02-02 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainlettersstories', '0003_sectiontrace'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSectionByUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('sectionid', models.IntegerField()),
            ],
            options={
                'db_table': 'availablesectionbyuser',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='section',
            name='previoussectionid',
            field=models.ForeignKey(db_column='sectionid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.section'),
        ),
    ]
