# Generated by Django 6.0.1 on 2026-03-12 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chainlettersstories', '0004_availablesegmentbyauthor_moderatablesegmentbyauthor_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='availablesegmentbyauthor',
            table='available_segment_by_user',
        ),
        migrations.AlterModelTable(
            name='moderatablesegmentbyauthor',
            table='moderatable_segment_by_user',
        ),
        migrations.AlterModelTable(
            name='segmenttrace',
            table='segment_trace',
        ),
    ]
