# Generated by Django 6.0.1 on 2026-02-03 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainlettersstories', '0004_availablesectionbyuser_section_previoussectionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='previoussectionid',
            field=models.ForeignKey(db_column='previoussectionid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.section'),
        ),
        migrations.CreateModel(
            name='ModerationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isitclosed', models.BooleanField()),
                ('sectionid', models.ForeignKey(db_column='sectionid', on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.section')),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.storiesuser')),
            ],
        ),
    ]
