# Generated by Django 6.0.1 on 2026-02-03 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainlettersstories', '0005_alter_section_previoussectionid_moderationassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationassignment',
            name='isitclosed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='isitclosed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='isitmature',
            field=models.BooleanField(default=False),
        ),
    ]
