# Generated by Django 6.0.1 on 2026-03-13 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chainlettersstories', '0005_alter_availablesegmentbyauthor_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='availablesegmentbyauthor',
            table='available_segment_by_author',
        ),
        migrations.AlterModelTable(
            name='moderatablesegmentbyauthor',
            table='moderatable_segment_by_author',
        ),
    ]
