# Generated by Django 6.0.1 on 2026-03-13 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chainlettersstories', '0006_alter_availablesegmentbyauthor_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailableSegmentByAuthor',
        ),
        migrations.DeleteModel(
            name='ModeratableSegmentByAuthor',
        ),
    ]
