# Generated by Django 6.0.1 on 2026-02-03 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainlettersstories', '0006_alter_moderationassignment_isitclosed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='textcontent',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
