# Generated by Django 6.0.1 on 2026-03-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainlettersstories', '0007_delete_availablesegmentbyauthor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSegmentByAuthor',
            fields=[
                ('pk', models.CompositePrimaryKey('author', 'segment', blank=True, editable=False, primary_key=True, serialize=False)),
                ('segment', models.IntegerField()),
            ],
            options={
                'db_table': 'available_segment_by_author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeratableSegmentByAuthor',
            fields=[
                ('pk', models.CompositePrimaryKey('author', 'segment', blank=True, editable=False, primary_key=True, serialize=False)),
                ('segment', models.IntegerField()),
            ],
            options={
                'db_table': 'moderatable_segment_by_author',
                'managed': False,
            },
        ),
    ]
