# Generated by Django 6.0.1 on 2026-03-06 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainlettersstories', '0007_alter_comment_textcontent_alter_section_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='maxstorylength',
            new_name='maxnumberofsections',
        ),
        migrations.AddField(
            model_name='story',
            name='maxnumberofbranches',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='minsectionlength',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='userid',
            field=models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sections', to='chainlettersstories.storiesuser'),
        ),
    ]
