# Generated by Django 6.0.1 on 2026-02-06 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainlettersstories', '0007_alter_comment_textcontent_alter_section_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='previoussectionid',
            field=models.ForeignKey(db_column='previoussectionid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.section'),
        ),
    ]
