# Generated by Django 6.0.1 on 2026-03-13 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chainlettersstories', '0008_availablesegmentbyauthor_moderatablesegmentbyauthor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailableSegmentByAuthor',
        ),
        migrations.DeleteModel(
            name='ModeratableSegmentByAuthor',
        ),
    ]
