# Generated by Django 6.0.1 on 2026-03-08 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainlettersstories', '0008_rename_maxstorylength_story_maxnumberofsections_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratableSectionByUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'moderatablesectionbyuser',
                'managed': False,
            },
        ),
    ]
