# Generated by Django 6.0.1 on 2026-03-16 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainlettersstories', '0010_availablesegmentbyauthor_moderatablesegmentbyauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='story_data', to='chainlettersstories.story'),
        ),
    ]
