# Generated by Django 6.0.1 on 2026-03-18 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainlettersstories', '0011_alter_segment_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CommentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(default='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.author')),
                ('comment_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.commentstatus')),
                ('comment_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.commenttype')),
            ],
        ),
        migrations.CreateModel(
            name='CommentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment_comment', to='chainlettersstories.comment')),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_comment_comment', to='chainlettersstories.comment')),
                ('comment_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.commenttype')),
            ],
        ),
        migrations.CreateModel(
            name='SegmentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='segment_comment', to='chainlettersstories.comment')),
                ('comment_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.commenttype')),
                ('parent_segment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_segment_comment', to='chainlettersstories.segment')),
            ],
        ),
        migrations.CreateModel(
            name='StoryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='story_comment', to='chainlettersstories.comment')),
                ('comment_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.commenttype')),
                ('parent_story', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_story_comment', to='chainlettersstories.story')),
            ],
        ),
    ]
