# Generated by Django 6.0.1 on 2026-03-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chainlettersstories', '0012_commentstatus_commenttype_comment_commentcomment_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='commentcomment',
            table='comment_comment',
        ),
        migrations.AlterModelTable(
            name='commentstatus',
            table='comment_status',
        ),
        migrations.AlterModelTable(
            name='commenttype',
            table='comment_type',
        ),
        migrations.AlterModelTable(
            name='segmentcomment',
            table='segment_comment',
        ),
        migrations.AlterModelTable(
            name='storycomment',
            table='story_comment',
        ),
    ]
