# Generated by Django 6.0.1 on 2026-03-18 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chainlettersstories', '0013_alter_comment_table_alter_commentcomment_table_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentType',
            new_name='CommentParentType',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_type',
            new_name='comment_parent_type',
        ),
        migrations.RenameField(
            model_name='commentcomment',
            old_name='comment_type',
            new_name='comment_parent_type',
        ),
        migrations.RenameField(
            model_name='segmentcomment',
            old_name='comment_type',
            new_name='comment_parent_type',
        ),
        migrations.RenameField(
            model_name='storycomment',
            old_name='comment_type',
            new_name='comment_parent_type',
        ),
        migrations.AlterModelTable(
            name='commentparenttype',
            table='comment_parent_type',
        ),
    ]
