# Generated by Django 6.0.1 on 2026-03-18 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainlettersstories', '0014_rename_commenttype_commentparenttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.commentstatus'),
        ),
    ]
