# Generated by Django 6.0.1 on 2026-03-18 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainlettersstories', '0015_alter_comment_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentcomment',
            name='comment_parent_type',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.commentparenttype'),
        ),
        migrations.AlterField(
            model_name='segmentcomment',
            name='comment_parent_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.commentparenttype'),
        ),
        migrations.AlterField(
            model_name='storycomment',
            name='comment_parent_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.commentparenttype'),
        ),
    ]
