# Generated by Django 6.0.1 on 2026-03-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainlettersstories', '0016_alter_commentcomment_comment_parent_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentCommentBySegment',
            fields=[
                ('pk', models.CompositePrimaryKey('segment', 'comment', blank=True, editable=False, primary_key=True, serialize=False)),
                ('text_content', models.CharField()),
            ],
            options={
                'db_table': 'segment_comment_by_segment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SegmentCommentCommentByComment',
            fields=[
                ('pk', models.CompositePrimaryKey('comment', 'child_comment', blank=True, editable=False, primary_key=True, serialize=False)),
                ('text_content', models.CharField()),
            ],
            options={
                'db_table': 'segment_comment_comment_by_comment',
                'managed': False,
            },
        ),
    ]
