# Generated by Django 6.0.1 on 2026-03-23 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainlettersstories', '0017_segmentcommentbysegment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorRelationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField()),
            ],
            options={
                'db_table': 'author_relation_type',
            },
        ),
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='AuthorRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.author')),
                ('related_author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_author', to='chainlettersstories.author')),
                ('author_relation_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.authorrelationtype')),
            ],
            options={
                'db_table': 'author_relation',
            },
        ),
        migrations.CreateModel(
            name='CircleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.author')),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.circle')),
            ],
        ),
    ]
