# Generated by Django 6.0.1 on 2026-03-23 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chainlettersstories', '0018_authorrelationtype_circle_authorrelation_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='circle',
            table='circle',
        ),
        migrations.AlterModelTable(
            name='circleassignment',
            table='circle_assignment',
        ),
    ]
