# Generated by Django 6.0.1 on 2026-03-24 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainlettersstories', '0019_alter_circle_table_alter_circleassignment_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circle',
            old_name='description',
            new_name='circle_name',
        ),
        migrations.AlterField(
            model_name='authorrelation',
            name='author_relation_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='chainlettersstories.authorrelationtype'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='segment', to='chainlettersstories.author'),
        ),
        migrations.AlterUniqueTogether(
            name='circleassignment',
            unique_together={('circle', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='moderationassignment',
            unique_together={('segment', 'author')},
        ),
    ]
