# Generated by Django 6.0.1 on 2026-03-24 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chainlettersstories', '0020_rename_description_circle_circle_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authorrelation',
            unique_together={('author', 'related_author')},
        ),
    ]
