--
-- PostgreSQL database dump
--

\restrict QrzUDQhelk8whjDct05f9fv7xpvVsq728BKDGcLquUrNXasf0UP6PxhwXxe77Nd

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

-- Started on 2026-03-26 17:32:54

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 285 (class 1259 OID 26194)
-- Name: author; Type: TABLE; Schema: chainlettersstoriesschema; Owner: -
--

CREATE TABLE chainlettersstoriesschema.author (
    id bigint CONSTRAINT chainlettersstories_author_id_not_null NOT NULL,
    display_name character varying(30) CONSTRAINT chainlettersstories_author_display_name_not_null NOT NULL,
    email character varying(30) CONSTRAINT chainlettersstories_author_email_not_null NOT NULL,
    password character varying(30) CONSTRAINT chainlettersstories_author_password_not_null NOT NULL
);


--
-- TOC entry 325 (class 1259 OID 27322)
-- Name: author_relation; Type: TABLE; Schema: chainlettersstoriesschema; Owner: -
--

CREATE TABLE chainlettersstoriesschema.author_relation (
    id bigint NOT NULL,
    author_id bigint NOT NULL,
    related_author_id bigint NOT NULL,
    author_relation_type_id bigint NOT NULL
);


--
-- TOC entry 324 (class 1259 OID 27321)
-- Name: author_relation_id_seq; Type: SEQUENCE; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE chainlettersstoriesschema.author_relation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chainlettersstoriesschema.author_relation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 321 (class 1259 OID 27302)
-- Name: author_relation_type; Type: TABLE; Schema: chainlettersstoriesschema; Owner: -
--

CREATE TABLE chainlettersstoriesschema.author_relation_type (
    id bigint NOT NULL,
    description character varying NOT NULL
);


--
-- TOC entry 320 (class 1259 OID 27301)
-- Name: author_relation_type_id_seq; Type: SEQUENCE; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE chainlettersstoriesschema.author_relation_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chainlettersstoriesschema.author_relation_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 291 (class 1259 OID 26219)
-- Name: segment; Type: TABLE; Schema: chainlettersstoriesschema; Owner: -
--

CREATE TABLE chainlettersstoriesschema.segment (
    id bigint CONSTRAINT chainlettersstories_segment_id_not_null NOT NULL,
    content text CONSTRAINT chainlettersstories_segment_content_not_null NOT NULL,
    previous_segment_id bigint,
    author_id bigint CONSTRAINT chainlettersstories_segment_user_id_not_null NOT NULL,
    segment_status_id bigint CONSTRAINT chainlettersstories_segment_segment_status_id_not_null NOT NULL,
    story_id bigint CONSTRAINT chainlettersstories_segment_story_id_not_null NOT NULL
);


--
-- TOC entry 299 (class 1259 OID 26368)
-- Name: segment_trace; Type: VIEW; Schema: chainlettersstoriesschema; Owner: -
--

CREATE VIEW chainlettersstoriesschema.segment_trace AS
 WITH RECURSIVE r(story_id, final_segment_id, segment_id, previous_segment_id, recursion_depth) AS (
         SELECT s_1.story_id,
            s_1.id,
            s_1.id,
            s_1.previous_segment_id,
            1 AS "?column?"
           FROM chainlettersstoriesschema.segment s_1
        UNION ALL
         SELECT r_1.story_id,
            r_1.final_segment_id,
            r_1.previous_segment_id,
            s2_1.previous_segment_id,
            (r_1.recursion_depth + 1)
           FROM (chainlettersstoriesschema.segment s2_1
             JOIN r r_1 ON (((r_1.story_id = s2_1.story_id) AND (r_1.previous_segment_id = s2_1.id))))
        )
 SELECT r.final_segment_id,
    r.segment_id AS earlier_segment_id,
    ((1 + ( SELECT max(r2.recursion_depth) AS max
           FROM r r2
          WHERE (r2.final_segment_id = r.final_segment_id))) - r.recursion_depth) AS earlier_segment_order,
    s.content AS earlier_segment_content,
    s2.author_id AS final_author_id,
    s2.segment_status_id AS final_segment_status_id,
    r.story_id,
    s.author_id AS earlier_segment_author_id
   FROM ((r
     JOIN chainlettersstoriesschema.segment s ON ((r.segment_id = s.id)))
     JOIN chainlettersstoriesschema.segment s2 ON ((r.final_segment_id = s2.id)))
  ORDER BY r.final_segment_id, ((1 + ( SELECT max(r2.recursion_depth) AS max
           FROM r r2
          WHERE (r2.final_segment_id = r.final_segment_id))) - r.recursion_depth);


--
-- TOC entry 300 (class 1259 OID 26374)
-- Name: available_segment_by_author; Type: VIEW; Schema: chainlettersstoriesschema; Owner: -
--

CREATE VIEW chainlettersstoriesschema.available_segment_by_author AS
 SELECT a.id AS author_id,
    s.id AS segment_id
   FROM (chainlettersstoriesschema.author a
     CROSS JOIN chainlettersstoriesschema.segment s)
  WHERE ((s.segment_status_id = 4) AND (NOT (EXISTS ( SELECT 1
           FROM (chainlettersstoriesschema.segment_trace st
             JOIN chainlettersstoriesschema.segment s2 ON ((st.earlier_segment_id = s2.id)))
          WHERE ((s2.author_id = a.id) AND (st.final_segment_id = s.id))))))
  ORDER BY a.id, s.id;


--
-- TOC entry 302 (class 1259 OID 26561)
-- Name: available_segment_by_user; Type: VIEW; Schema: chainlettersstoriesschema; Owner: -
--

CREATE VIEW chainlettersstoriesschema.available_segment_by_user AS
 SELECT a.id AS author_id,
    s.id AS segment_id
   FROM (chainlettersstoriesschema.author a
     CROSS JOIN chainlettersstoriesschema.segment s)
  WHERE ((s.segment_status_id = 4) AND (NOT (EXISTS ( SELECT 1
           FROM (chainlettersstoriesschema.segment_trace st
             JOIN chainlettersstoriesschema.segment s2 ON ((st.earlier_segment_id = s2.id)))
          WHERE ((s2.author_id = a.id) AND (st.final_segment_id = s.id))))));


--
-- TOC entry 284 (class 1259 OID 26193)
-- Name: chainlettersstories_author_id_seq; Type: SEQUENCE; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE chainlettersstoriesschema.author ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chainlettersstoriesschema.chainlettersstories_author_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 323 (class 1259 OID 27312)
-- Name: circle; Type: TABLE; Schema: chainlettersstoriesschema; Owner: -
--

CREATE TABLE chainlettersstoriesschema.circle (
    id bigint CONSTRAINT chainlettersstories_circle_id_not_null NOT NULL,
    circle_name character varying CONSTRAINT chainlettersstories_circle_description_not_null NOT NULL
);


--
-- TOC entry 322 (class 1259 OID 27311)
-- Name: chainlettersstories_circle_id_seq; Type: SEQUENCE; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE chainlettersstoriesschema.circle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chainlettersstoriesschema.chainlettersstories_circle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 327 (class 1259 OID 27332)
-- Name: circle_assignment; Type: TABLE; Schema: chainlettersstoriesschema; Owner: -
--

CREATE TABLE chainlettersstoriesschema.circle_assignment (
    id bigint CONSTRAINT chainlettersstories_circleassignment_id_not_null NOT NULL,
    author_id bigint CONSTRAINT chainlettersstories_circleassignment_author_id_not_null NOT NULL,
    circle_id bigint CONSTRAINT chainlettersstories_circleassignment_circle_id_not_null NOT NULL
);


--
-- TOC entry 326 (class 1259 OID 27331)
-- Name: chainlettersstories_circleassignment_id_seq; Type: SEQUENCE; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE chainlettersstoriesschema.circle_assignment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chainlettersstoriesschema.chainlettersstories_circleassignment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 309 (class 1259 OID 27129)
-- Name: comment; Type: TABLE; Schema: chainlettersstoriesschema; Owner: -
--

CREATE TABLE chainlettersstoriesschema.comment (
    id bigint CONSTRAINT chainlettersstories_comment_id_not_null NOT NULL,
    text_content text CONSTRAINT chainlettersstories_comment_text_content_not_null NOT NULL,
    author_id bigint CONSTRAINT chainlettersstories_comment_author_id_not_null NOT NULL,
    comment_status_id bigint CONSTRAINT chainlettersstories_comment_comment_status_id_not_null NOT NULL,
    comment_parent_type_id bigint CONSTRAINT chainlettersstories_comment_comment_type_id_not_null NOT NULL
);


--
-- TOC entry 308 (class 1259 OID 27128)
-- Name: chainlettersstories_comment_id_seq; Type: SEQUENCE; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE chainlettersstoriesschema.comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chainlettersstoriesschema.chainlettersstories_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 311 (class 1259 OID 27142)
-- Name: comment_comment; Type: TABLE; Schema: chainlettersstoriesschema; Owner: -
--

CREATE TABLE chainlettersstoriesschema.comment_comment (
    id bigint CONSTRAINT chainlettersstories_commentcomment_id_not_null NOT NULL,
    comment_id bigint CONSTRAINT chainlettersstories_commentcomment_comment_id_not_null NOT NULL,
    parent_comment_id bigint CONSTRAINT chainlettersstories_commentcomment_parent_comment_id_not_null NOT NULL,
    comment_parent_type_id bigint CONSTRAINT chainlettersstories_commentcomment_comment_type_id_not_null NOT NULL
);


--
-- TOC entry 310 (class 1259 OID 27141)
-- Name: chainlettersstories_commentcomment_id_seq; Type: SEQUENCE; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE chainlettersstoriesschema.comment_comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chainlettersstoriesschema.chainlettersstories_commentcomment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 305 (class 1259 OID 27113)
-- Name: comment_status; Type: TABLE; Schema: chainlettersstoriesschema; Owner: -
--

CREATE TABLE chainlettersstoriesschema.comment_status (
    id bigint CONSTRAINT chainlettersstories_commentstatus_id_not_null NOT NULL,
    description character varying(30) CONSTRAINT chainlettersstories_commentstatus_description_not_null NOT NULL
);


--
-- TOC entry 304 (class 1259 OID 27112)
-- Name: chainlettersstories_commentstatus_id_seq; Type: SEQUENCE; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE chainlettersstoriesschema.comment_status ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chainlettersstoriesschema.chainlettersstories_commentstatus_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 307 (class 1259 OID 27121)
-- Name: comment_parent_type; Type: TABLE; Schema: chainlettersstoriesschema; Owner: -
--

CREATE TABLE chainlettersstoriesschema.comment_parent_type (
    id bigint CONSTRAINT chainlettersstories_commenttype_id_not_null NOT NULL,
    description character varying(20) CONSTRAINT chainlettersstories_commenttype_description_not_null NOT NULL
);


--
-- TOC entry 306 (class 1259 OID 27120)
-- Name: chainlettersstories_commenttype_id_seq; Type: SEQUENCE; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE chainlettersstoriesschema.comment_parent_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chainlettersstoriesschema.chainlettersstories_commenttype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 293 (class 1259 OID 26231)
-- Name: moderation_assignment; Type: TABLE; Schema: chainlettersstoriesschema; Owner: -
--

CREATE TABLE chainlettersstoriesschema.moderation_assignment (
    id bigint CONSTRAINT chainlettersstories_moderationassignment_id_not_null NOT NULL,
    is_it_closed boolean CONSTRAINT chainlettersstories_moderationassignment_is_it_closed_not_null NOT NULL,
    author_id bigint CONSTRAINT chainlettersstories_moderationassignment_user_id_not_null NOT NULL,
    segment_id bigint CONSTRAINT chainlettersstories_moderationassignment_segment_id_not_null NOT NULL
);


--
-- TOC entry 292 (class 1259 OID 26230)
-- Name: chainlettersstories_moderationassignment_id_seq; Type: SEQUENCE; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE chainlettersstoriesschema.moderation_assignment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chainlettersstoriesschema.chainlettersstories_moderationassignment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 290 (class 1259 OID 26218)
-- Name: chainlettersstories_segment_id_seq; Type: SEQUENCE; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE chainlettersstoriesschema.segment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chainlettersstoriesschema.chainlettersstories_segment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 313 (class 1259 OID 27152)
-- Name: segment_comment; Type: TABLE; Schema: chainlettersstoriesschema; Owner: -
--

CREATE TABLE chainlettersstoriesschema.segment_comment (
    id bigint CONSTRAINT chainlettersstories_segmentcomment_id_not_null NOT NULL,
    comment_id bigint CONSTRAINT chainlettersstories_segmentcomment_comment_id_not_null NOT NULL,
    comment_parent_type_id bigint CONSTRAINT chainlettersstories_segmentcomment_comment_type_id_not_null NOT NULL,
    parent_segment_id bigint CONSTRAINT chainlettersstories_segmentcomment_parent_segment_id_not_null NOT NULL
);


--
-- TOC entry 312 (class 1259 OID 27151)
-- Name: chainlettersstories_segmentcomment_id_seq; Type: SEQUENCE; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE chainlettersstoriesschema.segment_comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chainlettersstoriesschema.chainlettersstories_segmentcomment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 287 (class 1259 OID 26204)
-- Name: segment_status; Type: TABLE; Schema: chainlettersstoriesschema; Owner: -
--

CREATE TABLE chainlettersstoriesschema.segment_status (
    id bigint CONSTRAINT chainlettersstories_segmentstatus_id_not_null NOT NULL,
    description character varying(30) CONSTRAINT chainlettersstories_segmentstatus_description_not_null NOT NULL
);


--
-- TOC entry 286 (class 1259 OID 26203)
-- Name: chainlettersstories_segmentstatus_id_seq; Type: SEQUENCE; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE chainlettersstoriesschema.segment_status ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chainlettersstoriesschema.chainlettersstories_segmentstatus_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 295 (class 1259 OID 26241)
-- Name: story; Type: TABLE; Schema: chainlettersstoriesschema; Owner: -
--

CREATE TABLE chainlettersstoriesschema.story (
    id bigint CONSTRAINT chainlettersstories_story_id_not_null NOT NULL,
    is_it_closed boolean CONSTRAINT chainlettersstories_story_is_it_closed_not_null NOT NULL,
    title character varying(100),
    min_segment_length smallint,
    max_segment_length smallint,
    max_number_of_segments smallint,
    max_number_of_branches smallint,
    is_it_mature boolean CONSTRAINT chainlettersstories_story_is_it_mature_not_null NOT NULL,
    author_id bigint CONSTRAINT chainlettersstories_story_user_id_not_null NOT NULL
);


--
-- TOC entry 294 (class 1259 OID 26240)
-- Name: chainlettersstories_story_id_seq; Type: SEQUENCE; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE chainlettersstoriesschema.story ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chainlettersstoriesschema.chainlettersstories_story_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 315 (class 1259 OID 27162)
-- Name: story_comment; Type: TABLE; Schema: chainlettersstoriesschema; Owner: -
--

CREATE TABLE chainlettersstoriesschema.story_comment (
    id bigint CONSTRAINT chainlettersstories_storycomment_id_not_null NOT NULL,
    comment_id bigint CONSTRAINT chainlettersstories_storycomment_comment_id_not_null NOT NULL,
    comment_parent_type_id bigint CONSTRAINT chainlettersstories_storycomment_comment_type_id_not_null NOT NULL,
    parent_story_id bigint CONSTRAINT chainlettersstories_storycomment_parent_story_id_not_null NOT NULL
);


--
-- TOC entry 314 (class 1259 OID 27161)
-- Name: chainlettersstories_storycomment_id_seq; Type: SEQUENCE; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE chainlettersstoriesschema.story_comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chainlettersstoriesschema.chainlettersstories_storycomment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 289 (class 1259 OID 26212)
-- Name: tag; Type: TABLE; Schema: chainlettersstoriesschema; Owner: -
--

CREATE TABLE chainlettersstoriesschema.tag (
    id bigint CONSTRAINT chainlettersstories_tag_id_not_null NOT NULL,
    description character varying(20)
);


--
-- TOC entry 288 (class 1259 OID 26211)
-- Name: chainlettersstories_tag_id_seq; Type: SEQUENCE; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE chainlettersstoriesschema.tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chainlettersstoriesschema.chainlettersstories_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 297 (class 1259 OID 26257)
-- Name: tag_assignment; Type: TABLE; Schema: chainlettersstoriesschema; Owner: -
--

CREATE TABLE chainlettersstoriesschema.tag_assignment (
    id bigint CONSTRAINT chainlettersstories_tagassingment_id_not_null NOT NULL,
    story_id bigint CONSTRAINT chainlettersstories_tagassingment_story_id_not_null NOT NULL,
    tagid_id bigint CONSTRAINT chainlettersstories_tagassingment_tagid_id_not_null NOT NULL
);


--
-- TOC entry 296 (class 1259 OID 26256)
-- Name: chainlettersstories_tagassingment_id_seq; Type: SEQUENCE; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE chainlettersstoriesschema.tag_assignment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chainlettersstoriesschema.chainlettersstories_tagassingment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 316 (class 1259 OID 27284)
-- Name: segment_comment_by_segment; Type: VIEW; Schema: chainlettersstoriesschema; Owner: -
--

CREATE VIEW chainlettersstoriesschema.segment_comment_by_segment AS
 SELECT s.id AS segment_id,
    sc.comment_id,
    c.author_id,
    c.text_content
   FROM ((chainlettersstoriesschema.segment s
     JOIN chainlettersstoriesschema.segment_comment sc ON ((sc.parent_segment_id = s.id)))
     JOIN chainlettersstoriesschema.comment c ON ((c.id = sc.comment_id)));


--
-- TOC entry 317 (class 1259 OID 27288)
-- Name: comment_comment_by_comment; Type: VIEW; Schema: chainlettersstoriesschema; Owner: -
--

CREATE VIEW chainlettersstoriesschema.comment_comment_by_comment AS
 SELECT scbs.segment_id,
    scbs.comment_id,
    cc.comment_id AS child_comment_id,
    c.author_id,
    c.text_content
   FROM ((chainlettersstoriesschema.segment_comment_by_segment scbs
     JOIN chainlettersstoriesschema.comment_comment cc ON ((cc.parent_comment_id = scbs.comment_id)))
     JOIN chainlettersstoriesschema.comment c ON ((c.id = cc.comment_id)));


--
-- TOC entry 318 (class 1259 OID 27292)
-- Name: comment_comment_by_segment; Type: VIEW; Schema: chainlettersstoriesschema; Owner: -
--

CREATE VIEW chainlettersstoriesschema.comment_comment_by_segment AS
 SELECT scbs.comment_id,
    cc.comment_id AS child_comment_id,
    c.author_id,
    c.text_content
   FROM ((chainlettersstoriesschema.segment_comment_by_segment scbs
     JOIN chainlettersstoriesschema.comment_comment cc ON ((cc.parent_comment_id = scbs.comment_id)))
     JOIN chainlettersstoriesschema.comment c ON ((c.id = cc.comment_id)));


--
-- TOC entry 301 (class 1259 OID 26379)
-- Name: moderatable_segment_by_author; Type: VIEW; Schema: chainlettersstoriesschema; Owner: -
--

CREATE VIEW chainlettersstoriesschema.moderatable_segment_by_author AS
 SELECT a.id AS author_id,
    s.id AS segment_id
   FROM (chainlettersstoriesschema.author a
     CROSS JOIN chainlettersstoriesschema.segment s)
  WHERE ((s.segment_status_id = 2) AND (s.author_id <> a.id));


--
-- TOC entry 319 (class 1259 OID 27296)
-- Name: segment_comment_comment_by_comment; Type: VIEW; Schema: chainlettersstoriesschema; Owner: -
--

CREATE VIEW chainlettersstoriesschema.segment_comment_comment_by_comment AS
 SELECT scbs.comment_id,
    cc.comment_id AS child_comment_id,
    c.author_id,
    c.text_content
   FROM ((chainlettersstoriesschema.segment_comment_by_segment scbs
     JOIN chainlettersstoriesschema.comment_comment cc ON ((cc.parent_comment_id = scbs.comment_id)))
     JOIN chainlettersstoriesschema.comment c ON ((c.id = cc.comment_id)));


--
-- TOC entry 5141 (class 2606 OID 27380)
-- Name: author_relation author_relation_author_id_related_author_id_00aa0f31_uniq; Type: CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.author_relation
    ADD CONSTRAINT author_relation_author_id_related_author_id_00aa0f31_uniq UNIQUE (author_id, related_author_id);


--
-- TOC entry 5144 (class 2606 OID 27330)
-- Name: author_relation author_relation_pkey; Type: CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.author_relation
    ADD CONSTRAINT author_relation_pkey PRIMARY KEY (id);


--
-- TOC entry 5136 (class 2606 OID 27310)
-- Name: author_relation_type author_relation_type_pkey; Type: CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.author_relation_type
    ADD CONSTRAINT author_relation_type_pkey PRIMARY KEY (id);


--
-- TOC entry 5087 (class 2606 OID 26202)
-- Name: author chainlettersstories_author_pkey; Type: CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.author
    ADD CONSTRAINT chainlettersstories_author_pkey PRIMARY KEY (id);


--
-- TOC entry 5138 (class 2606 OID 27320)
-- Name: circle chainlettersstories_circle_pkey; Type: CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.circle
    ADD CONSTRAINT chainlettersstories_circle_pkey PRIMARY KEY (id);


--
-- TOC entry 5149 (class 2606 OID 27339)
-- Name: circle_assignment chainlettersstories_circleassignment_pkey; Type: CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.circle_assignment
    ADD CONSTRAINT chainlettersstories_circleassignment_pkey PRIMARY KEY (id);


--
-- TOC entry 5119 (class 2606 OID 27140)
-- Name: comment chainlettersstories_comment_pkey; Type: CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.comment
    ADD CONSTRAINT chainlettersstories_comment_pkey PRIMARY KEY (id);


--
-- TOC entry 5124 (class 2606 OID 27150)
-- Name: comment_comment chainlettersstories_commentcomment_pkey; Type: CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.comment_comment
    ADD CONSTRAINT chainlettersstories_commentcomment_pkey PRIMARY KEY (id);


--
-- TOC entry 5112 (class 2606 OID 27119)
-- Name: comment_status chainlettersstories_commentstatus_pkey; Type: CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.comment_status
    ADD CONSTRAINT chainlettersstories_commentstatus_pkey PRIMARY KEY (id);


--
-- TOC entry 5114 (class 2606 OID 27127)
-- Name: comment_parent_type chainlettersstories_commenttype_pkey; Type: CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.comment_parent_type
    ADD CONSTRAINT chainlettersstories_commenttype_pkey PRIMARY KEY (id);


--
-- TOC entry 5099 (class 2606 OID 26239)
-- Name: moderation_assignment chainlettersstories_moderationassignment_pkey; Type: CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.moderation_assignment
    ADD CONSTRAINT chainlettersstories_moderationassignment_pkey PRIMARY KEY (id);


--
-- TOC entry 5093 (class 2606 OID 26229)
-- Name: segment chainlettersstories_segment_pkey; Type: CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.segment
    ADD CONSTRAINT chainlettersstories_segment_pkey PRIMARY KEY (id);


--
-- TOC entry 5129 (class 2606 OID 27160)
-- Name: segment_comment chainlettersstories_segmentcomment_pkey; Type: CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.segment_comment
    ADD CONSTRAINT chainlettersstories_segmentcomment_pkey PRIMARY KEY (id);


--
-- TOC entry 5089 (class 2606 OID 26210)
-- Name: segment_status chainlettersstories_segmentstatus_pkey; Type: CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.segment_status
    ADD CONSTRAINT chainlettersstories_segmentstatus_pkey PRIMARY KEY (id);


--
-- TOC entry 5105 (class 2606 OID 26249)
-- Name: story chainlettersstories_story_pkey; Type: CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.story
    ADD CONSTRAINT chainlettersstories_story_pkey PRIMARY KEY (id);


--
-- TOC entry 5134 (class 2606 OID 27170)
-- Name: story_comment chainlettersstories_storycomment_pkey; Type: CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.story_comment
    ADD CONSTRAINT chainlettersstories_storycomment_pkey PRIMARY KEY (id);


--
-- TOC entry 5091 (class 2606 OID 26217)
-- Name: tag chainlettersstories_tag_pkey; Type: CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.tag
    ADD CONSTRAINT chainlettersstories_tag_pkey PRIMARY KEY (id);


--
-- TOC entry 5108 (class 2606 OID 26264)
-- Name: tag_assignment chainlettersstories_tagassingment_pkey; Type: CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.tag_assignment
    ADD CONSTRAINT chainlettersstories_tagassingment_pkey PRIMARY KEY (id);


--
-- TOC entry 5151 (class 2606 OID 27376)
-- Name: circle_assignment circle_assignment_circle_id_author_id_e8775e2d_uniq; Type: CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.circle_assignment
    ADD CONSTRAINT circle_assignment_circle_id_author_id_e8775e2d_uniq UNIQUE (circle_id, author_id);


--
-- TOC entry 5103 (class 2606 OID 27378)
-- Name: moderation_assignment moderation_assignment_segment_id_author_id_b24140c6_uniq; Type: CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.moderation_assignment
    ADD CONSTRAINT moderation_assignment_segment_id_author_id_b24140c6_uniq UNIQUE (segment_id, author_id);


--
-- TOC entry 5139 (class 1259 OID 27355)
-- Name: author_relation_author_id_57557516; Type: INDEX; Schema: chainlettersstoriesschema; Owner: -
--

CREATE INDEX author_relation_author_id_57557516 ON chainlettersstoriesschema.author_relation USING btree (author_id);


--
-- TOC entry 5142 (class 1259 OID 27357)
-- Name: author_relation_author_relation_type_id_32b0701e; Type: INDEX; Schema: chainlettersstoriesschema; Owner: -
--

CREATE INDEX author_relation_author_relation_type_id_32b0701e ON chainlettersstoriesschema.author_relation USING btree (author_relation_type_id);


--
-- TOC entry 5145 (class 1259 OID 27356)
-- Name: author_relation_related_author_id_4e94a641; Type: INDEX; Schema: chainlettersstoriesschema; Owner: -
--

CREATE INDEX author_relation_related_author_id_4e94a641 ON chainlettersstoriesschema.author_relation USING btree (related_author_id);


--
-- TOC entry 5146 (class 1259 OID 27368)
-- Name: chainlettersstories_circleassignment_author_id_5830ac48; Type: INDEX; Schema: chainlettersstoriesschema; Owner: -
--

CREATE INDEX chainlettersstories_circleassignment_author_id_5830ac48 ON chainlettersstoriesschema.circle_assignment USING btree (author_id);


--
-- TOC entry 5147 (class 1259 OID 27369)
-- Name: chainlettersstories_circleassignment_circle_id_842a5a5c; Type: INDEX; Schema: chainlettersstoriesschema; Owner: -
--

CREATE INDEX chainlettersstories_circleassignment_circle_id_842a5a5c ON chainlettersstoriesschema.circle_assignment USING btree (circle_id);


--
-- TOC entry 5115 (class 1259 OID 27186)
-- Name: chainlettersstories_comment_author_id_499719ea; Type: INDEX; Schema: chainlettersstoriesschema; Owner: -
--

CREATE INDEX chainlettersstories_comment_author_id_499719ea ON chainlettersstoriesschema.comment USING btree (author_id);


--
-- TOC entry 5116 (class 1259 OID 27187)
-- Name: chainlettersstories_comment_comment_status_id_946493b2; Type: INDEX; Schema: chainlettersstoriesschema; Owner: -
--

CREATE INDEX chainlettersstories_comment_comment_status_id_946493b2 ON chainlettersstoriesschema.comment USING btree (comment_status_id);


--
-- TOC entry 5117 (class 1259 OID 27188)
-- Name: chainlettersstories_comment_comment_type_id_c93c2aeb; Type: INDEX; Schema: chainlettersstoriesschema; Owner: -
--

CREATE INDEX chainlettersstories_comment_comment_type_id_c93c2aeb ON chainlettersstoriesschema.comment USING btree (comment_parent_type_id);


--
-- TOC entry 5120 (class 1259 OID 27204)
-- Name: chainlettersstories_commentcomment_comment_id_c35905cf; Type: INDEX; Schema: chainlettersstoriesschema; Owner: -
--

CREATE INDEX chainlettersstories_commentcomment_comment_id_c35905cf ON chainlettersstoriesschema.comment_comment USING btree (comment_id);


--
-- TOC entry 5121 (class 1259 OID 27206)
-- Name: chainlettersstories_commentcomment_comment_type_id_1cdaf1cb; Type: INDEX; Schema: chainlettersstoriesschema; Owner: -
--

CREATE INDEX chainlettersstories_commentcomment_comment_type_id_1cdaf1cb ON chainlettersstoriesschema.comment_comment USING btree (comment_parent_type_id);


--
-- TOC entry 5122 (class 1259 OID 27205)
-- Name: chainlettersstories_commentcomment_parent_comment_id_1ab3218b; Type: INDEX; Schema: chainlettersstoriesschema; Owner: -
--

CREATE INDEX chainlettersstories_commentcomment_parent_comment_id_1ab3218b ON chainlettersstoriesschema.comment_comment USING btree (parent_comment_id);


--
-- TOC entry 5100 (class 1259 OID 26294)
-- Name: chainlettersstories_moderationassignment_segment_id_916be8eb; Type: INDEX; Schema: chainlettersstoriesschema; Owner: -
--

CREATE INDEX chainlettersstories_moderationassignment_segment_id_916be8eb ON chainlettersstoriesschema.moderation_assignment USING btree (segment_id);


--
-- TOC entry 5101 (class 1259 OID 26293)
-- Name: chainlettersstories_moderationassignment_user_id_4acdda9c; Type: INDEX; Schema: chainlettersstoriesschema; Owner: -
--

CREATE INDEX chainlettersstories_moderationassignment_user_id_4acdda9c ON chainlettersstoriesschema.moderation_assignment USING btree (author_id);


--
-- TOC entry 5094 (class 1259 OID 26280)
-- Name: chainlettersstories_segment_previous_segment_id_1b79c292; Type: INDEX; Schema: chainlettersstoriesschema; Owner: -
--

CREATE INDEX chainlettersstories_segment_previous_segment_id_1b79c292 ON chainlettersstoriesschema.segment USING btree (previous_segment_id);


--
-- TOC entry 5095 (class 1259 OID 26282)
-- Name: chainlettersstories_segment_segment_status_id_5bf973cd; Type: INDEX; Schema: chainlettersstoriesschema; Owner: -
--

CREATE INDEX chainlettersstories_segment_segment_status_id_5bf973cd ON chainlettersstoriesschema.segment USING btree (segment_status_id);


--
-- TOC entry 5096 (class 1259 OID 26301)
-- Name: chainlettersstories_segment_story_id_d92a3c17; Type: INDEX; Schema: chainlettersstoriesschema; Owner: -
--

CREATE INDEX chainlettersstories_segment_story_id_d92a3c17 ON chainlettersstoriesschema.segment USING btree (story_id);


--
-- TOC entry 5097 (class 1259 OID 26281)
-- Name: chainlettersstories_segment_user_id_25cdc297; Type: INDEX; Schema: chainlettersstoriesschema; Owner: -
--

CREATE INDEX chainlettersstories_segment_user_id_25cdc297 ON chainlettersstoriesschema.segment USING btree (author_id);


--
-- TOC entry 5125 (class 1259 OID 27222)
-- Name: chainlettersstories_segmentcomment_comment_id_775c433c; Type: INDEX; Schema: chainlettersstoriesschema; Owner: -
--

CREATE INDEX chainlettersstories_segmentcomment_comment_id_775c433c ON chainlettersstoriesschema.segment_comment USING btree (comment_id);


--
-- TOC entry 5126 (class 1259 OID 27223)
-- Name: chainlettersstories_segmentcomment_comment_type_id_b2f4e8f1; Type: INDEX; Schema: chainlettersstoriesschema; Owner: -
--

CREATE INDEX chainlettersstories_segmentcomment_comment_type_id_b2f4e8f1 ON chainlettersstoriesschema.segment_comment USING btree (comment_parent_type_id);


--
-- TOC entry 5127 (class 1259 OID 27224)
-- Name: chainlettersstories_segmentcomment_parent_segment_id_c316baee; Type: INDEX; Schema: chainlettersstoriesschema; Owner: -
--

CREATE INDEX chainlettersstories_segmentcomment_parent_segment_id_c316baee ON chainlettersstoriesschema.segment_comment USING btree (parent_segment_id);


--
-- TOC entry 5106 (class 1259 OID 26300)
-- Name: chainlettersstories_story_user_id_c9c736af; Type: INDEX; Schema: chainlettersstoriesschema; Owner: -
--

CREATE INDEX chainlettersstories_story_user_id_c9c736af ON chainlettersstoriesschema.story USING btree (author_id);


--
-- TOC entry 5130 (class 1259 OID 27240)
-- Name: chainlettersstories_storycomment_comment_id_c7daf5e9; Type: INDEX; Schema: chainlettersstoriesschema; Owner: -
--

CREATE INDEX chainlettersstories_storycomment_comment_id_c7daf5e9 ON chainlettersstoriesschema.story_comment USING btree (comment_id);


--
-- TOC entry 5131 (class 1259 OID 27241)
-- Name: chainlettersstories_storycomment_comment_type_id_b47c62a2; Type: INDEX; Schema: chainlettersstoriesschema; Owner: -
--

CREATE INDEX chainlettersstories_storycomment_comment_type_id_b47c62a2 ON chainlettersstoriesschema.story_comment USING btree (comment_parent_type_id);


--
-- TOC entry 5132 (class 1259 OID 27242)
-- Name: chainlettersstories_storycomment_parent_story_id_88ca02a1; Type: INDEX; Schema: chainlettersstoriesschema; Owner: -
--

CREATE INDEX chainlettersstories_storycomment_parent_story_id_88ca02a1 ON chainlettersstoriesschema.story_comment USING btree (parent_story_id);


--
-- TOC entry 5109 (class 1259 OID 26312)
-- Name: chainlettersstories_tagassingment_story_id_6de2f422; Type: INDEX; Schema: chainlettersstoriesschema; Owner: -
--

CREATE INDEX chainlettersstories_tagassingment_story_id_6de2f422 ON chainlettersstoriesschema.tag_assignment USING btree (story_id);


--
-- TOC entry 5110 (class 1259 OID 26313)
-- Name: chainlettersstories_tagassingment_tagid_id_49c6fc71; Type: INDEX; Schema: chainlettersstoriesschema; Owner: -
--

CREATE INDEX chainlettersstories_tagassingment_tagid_id_49c6fc71 ON chainlettersstoriesschema.tag_assignment USING btree (tagid_id);


--
-- TOC entry 5173 (class 2606 OID 27340)
-- Name: author_relation author_relation_author_id_57557516_fk_author_id; Type: FK CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.author_relation
    ADD CONSTRAINT author_relation_author_id_57557516_fk_author_id FOREIGN KEY (author_id) REFERENCES chainlettersstoriesschema.author(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5174 (class 2606 OID 27370)
-- Name: author_relation author_relation_author_relation_type_32b0701e_fk_author_re; Type: FK CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.author_relation
    ADD CONSTRAINT author_relation_author_relation_type_32b0701e_fk_author_re FOREIGN KEY (author_relation_type_id) REFERENCES chainlettersstoriesschema.author_relation_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5175 (class 2606 OID 27345)
-- Name: author_relation author_relation_related_author_id_4e94a641_fk_author_id; Type: FK CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.author_relation
    ADD CONSTRAINT author_relation_related_author_id_4e94a641_fk_author_id FOREIGN KEY (related_author_id) REFERENCES chainlettersstoriesschema.author(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5176 (class 2606 OID 27358)
-- Name: circle_assignment chainlettersstories__author_id_5830ac48_fk_author_id; Type: FK CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.circle_assignment
    ADD CONSTRAINT chainlettersstories__author_id_5830ac48_fk_author_id FOREIGN KEY (author_id) REFERENCES chainlettersstoriesschema.author(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5177 (class 2606 OID 27363)
-- Name: circle_assignment chainlettersstories__circle_id_842a5a5c_fk_chainlett; Type: FK CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.circle_assignment
    ADD CONSTRAINT chainlettersstories__circle_id_842a5a5c_fk_chainlett FOREIGN KEY (circle_id) REFERENCES chainlettersstoriesschema.circle(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5167 (class 2606 OID 27207)
-- Name: segment_comment chainlettersstories__comment_id_775c433c_fk_chainlett; Type: FK CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.segment_comment
    ADD CONSTRAINT chainlettersstories__comment_id_775c433c_fk_chainlett FOREIGN KEY (comment_id) REFERENCES chainlettersstoriesschema.comment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5164 (class 2606 OID 27189)
-- Name: comment_comment chainlettersstories__comment_id_c35905cf_fk_chainlett; Type: FK CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.comment_comment
    ADD CONSTRAINT chainlettersstories__comment_id_c35905cf_fk_chainlett FOREIGN KEY (comment_id) REFERENCES chainlettersstoriesschema.comment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5170 (class 2606 OID 27225)
-- Name: story_comment chainlettersstories__comment_id_c7daf5e9_fk_chainlett; Type: FK CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.story_comment
    ADD CONSTRAINT chainlettersstories__comment_id_c7daf5e9_fk_chainlett FOREIGN KEY (comment_id) REFERENCES chainlettersstoriesschema.comment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5165 (class 2606 OID 27194)
-- Name: comment_comment chainlettersstories__parent_comment_id_1ab3218b_fk_chainlett; Type: FK CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.comment_comment
    ADD CONSTRAINT chainlettersstories__parent_comment_id_1ab3218b_fk_chainlett FOREIGN KEY (parent_comment_id) REFERENCES chainlettersstoriesschema.comment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5168 (class 2606 OID 27217)
-- Name: segment_comment chainlettersstories__parent_segment_id_c316baee_fk_segment_i; Type: FK CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.segment_comment
    ADD CONSTRAINT chainlettersstories__parent_segment_id_c316baee_fk_segment_i FOREIGN KEY (parent_segment_id) REFERENCES chainlettersstoriesschema.segment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5171 (class 2606 OID 27235)
-- Name: story_comment chainlettersstories__parent_story_id_88ca02a1_fk_story_id; Type: FK CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.story_comment
    ADD CONSTRAINT chainlettersstories__parent_story_id_88ca02a1_fk_story_id FOREIGN KEY (parent_story_id) REFERENCES chainlettersstoriesschema.story(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5152 (class 2606 OID 26265)
-- Name: segment chainlettersstories__previous_segment_id_1b79c292_fk_chainlett; Type: FK CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.segment
    ADD CONSTRAINT chainlettersstories__previous_segment_id_1b79c292_fk_chainlett FOREIGN KEY (previous_segment_id) REFERENCES chainlettersstoriesschema.segment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5156 (class 2606 OID 26288)
-- Name: moderation_assignment chainlettersstories__segment_id_916be8eb_fk_chainlett; Type: FK CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.moderation_assignment
    ADD CONSTRAINT chainlettersstories__segment_id_916be8eb_fk_chainlett FOREIGN KEY (segment_id) REFERENCES chainlettersstoriesschema.segment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5153 (class 2606 OID 26275)
-- Name: segment chainlettersstories__segment_status_id_5bf973cd_fk_chainlett; Type: FK CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.segment
    ADD CONSTRAINT chainlettersstories__segment_status_id_5bf973cd_fk_chainlett FOREIGN KEY (segment_status_id) REFERENCES chainlettersstoriesschema.segment_status(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5159 (class 2606 OID 26302)
-- Name: tag_assignment chainlettersstories__story_id_6de2f422_fk_chainlett; Type: FK CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.tag_assignment
    ADD CONSTRAINT chainlettersstories__story_id_6de2f422_fk_chainlett FOREIGN KEY (story_id) REFERENCES chainlettersstoriesschema.story(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5154 (class 2606 OID 26251)
-- Name: segment chainlettersstories__story_id_d92a3c17_fk_chainlett; Type: FK CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.segment
    ADD CONSTRAINT chainlettersstories__story_id_d92a3c17_fk_chainlett FOREIGN KEY (story_id) REFERENCES chainlettersstoriesschema.story(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5160 (class 2606 OID 26307)
-- Name: tag_assignment chainlettersstories__tagid_id_49c6fc71_fk_chainlett; Type: FK CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.tag_assignment
    ADD CONSTRAINT chainlettersstories__tagid_id_49c6fc71_fk_chainlett FOREIGN KEY (tagid_id) REFERENCES chainlettersstoriesschema.tag(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5161 (class 2606 OID 27171)
-- Name: comment chainlettersstories_comment_author_id_499719ea_fk_author_id; Type: FK CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.comment
    ADD CONSTRAINT chainlettersstories_comment_author_id_499719ea_fk_author_id FOREIGN KEY (author_id) REFERENCES chainlettersstoriesschema.author(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5166 (class 2606 OID 27268)
-- Name: comment_comment comment_comment_comment_parent_type__f1827fe0_fk_comment_p; Type: FK CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.comment_comment
    ADD CONSTRAINT comment_comment_comment_parent_type__f1827fe0_fk_comment_p FOREIGN KEY (comment_parent_type_id) REFERENCES chainlettersstoriesschema.comment_parent_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5162 (class 2606 OID 27243)
-- Name: comment comment_comment_parent_type_id_23011e2c_fk_comment_type_id; Type: FK CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.comment
    ADD CONSTRAINT comment_comment_parent_type_id_23011e2c_fk_comment_type_id FOREIGN KEY (comment_parent_type_id) REFERENCES chainlettersstoriesschema.comment_parent_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5163 (class 2606 OID 27263)
-- Name: comment comment_comment_status_id_1a26e217_fk_comment_status_id; Type: FK CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.comment
    ADD CONSTRAINT comment_comment_status_id_1a26e217_fk_comment_status_id FOREIGN KEY (comment_status_id) REFERENCES chainlettersstoriesschema.comment_status(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5157 (class 2606 OID 26334)
-- Name: moderation_assignment moderation_assignment_author_id_2171d364_fk_author_id; Type: FK CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.moderation_assignment
    ADD CONSTRAINT moderation_assignment_author_id_2171d364_fk_author_id FOREIGN KEY (author_id) REFERENCES chainlettersstoriesschema.author(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5155 (class 2606 OID 26339)
-- Name: segment segment_author_id_e8ebddaa_fk_author_id; Type: FK CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.segment
    ADD CONSTRAINT segment_author_id_e8ebddaa_fk_author_id FOREIGN KEY (author_id) REFERENCES chainlettersstoriesschema.author(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5169 (class 2606 OID 27273)
-- Name: segment_comment segment_comment_comment_parent_type__82ecc826_fk_comment_p; Type: FK CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.segment_comment
    ADD CONSTRAINT segment_comment_comment_parent_type__82ecc826_fk_comment_p FOREIGN KEY (comment_parent_type_id) REFERENCES chainlettersstoriesschema.comment_parent_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5158 (class 2606 OID 26344)
-- Name: story story_author_id_1237409a_fk_author_id; Type: FK CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.story
    ADD CONSTRAINT story_author_id_1237409a_fk_author_id FOREIGN KEY (author_id) REFERENCES chainlettersstoriesschema.author(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5172 (class 2606 OID 27278)
-- Name: story_comment story_comment_comment_parent_type__875c4325_fk_comment_p; Type: FK CONSTRAINT; Schema: chainlettersstoriesschema; Owner: -
--

ALTER TABLE ONLY chainlettersstoriesschema.story_comment
    ADD CONSTRAINT story_comment_comment_parent_type__875c4325_fk_comment_p FOREIGN KEY (comment_parent_type_id) REFERENCES chainlettersstoriesschema.comment_parent_type(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2026-03-26 17:32:55

--
-- PostgreSQL database dump complete
--

\unrestrict QrzUDQhelk8whjDct05f9fv7xpvVsq728BKDGcLquUrNXasf0UP6PxhwXxe77Nd

